services:
  dc-frontend:
    hostname: frontend
    image: ghcr.io/svenfinn/dc-frontend:${APP_VERSION}
    container_name: dc-frontend
    restart: unless-stopped
    networks:
      - displaycontroller
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        - range-types=../ranges/types
        - screen-types=../screens/screenManager/types
      args:
        - APP_PORT=${APP_PORT}
        - MAX_MEYTON_VERSION=${MAX_MEYTON_VERSION}
        - MIN_MEYTON_VERSION=${MIN_MEYTON_VERSION}
        - APP_VERSION=${APP_VERSION}
