services:
  dc-frontend:
    hostname: frontend
    image: ghcr.io/svenfinn/dc-frontend:${APP_VERSION}
    container_name: dc-frontend
    restart: on-failure
    networks:
      - displaycontroller
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        - logger=../lib/logger
        - endpoints=../lib/endpoints
        - ranges-contract=../ranges/contract
        - screen-types=../screens/types
        - files-utils=../screens/utils/files
      args:
        - APP_PORT=${APP_PORT}
        - HTTPS_PORT=${HTTPS_PORT}
        - MAX_SM_VERSION=${MAX_SM_VERSION}
        - MIN_SM_VERSION=${MIN_SM_VERSION}
        - APP_VERSION=${APP_VERSION}
