services:
  dc-images:
    container_name: dc-images
    image: ghcr.io/svenfinn/dc-images:${APP_VERSION}
    hostname: images
    restart: on-failure
    networks:
      - displaycontroller
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        - logger=../../logger
        - files-utils=../utils/files
    volumes:
      - images_data:/app/files
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - SCREEN_RESOLUTION=${SCREEN_RESOLUTION}

volumes:
  images_data:
