services:
  dc-reverse-proxy:
    container_name: dc-reverse_proxy
    hostname: reverse_proxy
    build: .
    ports:
      - "80:80"
    networks:
      - displaycontroller
    depends_on:
      dc-db-migrate:
        condition: service_completed_successfully