services:
  dc-ranges-ssmdb2:
    container_name: dc-ranges-ssmdb2
    image: ghcr.io/svenfinn/dc-ranges-ssmdb2:${APP_VERSION}
    hostname: ranges-ssmdb2
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SELF_DB_HOST=${SELF_DB_HOST}
        - SELF_DB_USER=${SELF_DB_USER}
        - SELF_DB_PASS=${SELF_DB_PASS}
        - SELF_DB_NAME=${SELF_DB_NAME}
        - MEYTON_DB_USER=${MEYTON_DB_USER}
        - MEYTON_DB_PASS=${MEYTON_DB_PASS}
        - CACHE_REFRESH_INTERVAL=${CACHE_REFRESH_INTERVAL}
      additional_contexts:
        - local-db=../../database/local
        - ssmdb2=../../database/ssmdb2
        - range-types=../types
        - table-watcher=../../database/tableWatcher
        - logger=../../logger
    networks:
      - displaycontroller
    depends_on:
      dc-db-migrate:
        condition: service_completed_successfully
      dc-rabbitmq:
        condition: service_healthy
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
