services:
  dc-ranges-ssmdb2:
    container_name: dc-ranges-ssmdb2
    image: ghcr.io/svenfinn/dc-ranges-ssmdb2:${APP_VERSION}
    hostname: ranges-ssmdb2
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SELF_DB_HOST=${SELF_DB_HOST}
        - SELF_DB_USER=${SELF_DB_USER}
        - SELF_DB_PASS=${SELF_DB_PASS}
        - SELF_DB_NAME=${SELF_DB_NAME}
        - SM_DB_USER=${SM_DB_USER}
        - SM_DB_PASS=${SM_DB_PASS}
        - CACHE_REFRESH_INTERVAL=${CACHE_REFRESH_INTERVAL}
      additional_contexts:
        - local-db=../../lib/database/local
        - ssmdb2=../../lib/database/ssmdb2
        - endpoints=../../lib/endpoints
        - ranges=../ranges
        - table-watcher=../../lib/database/tableWatcher
        - logger=../../lib/logger
        - streams=../../lib/streams
    networks:
      - displaycontroller
    depends_on:
      dc-database:
        condition: service_healthy
      dc-db-migrate:
        condition: service_completed_successfully
      dc-rabbitmq:
        condition: service_healthy
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
