services:
  dc_db_migrate:
    container_name: dc-db-migrate
    networks:
      - displaycontroller
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - SELF_DB_URL=${SELF_DB_URL}