services:
  dc-rabbitmq:
    container_name: dc-rabbitmq
    image: ghcr.io/svenfinn/dc-rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - displaycontroller
    ports:
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 3
