include:
  - ./proxy/docker-compose.yaml

services:
  dc-ranges-multicast:
    container_name: dc-ranges-multicast
    image: ghcr.io/svenfinn/dc-ranges-multicast
    hostname: multicast
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SELF_DB_URL=${SELF_DB_URL}
      additional_contexts:
        - local-db=../../database/local
        - range-types=../types
        - logger=../../logger
    networks:
      - displaycontroller
    depends_on:
      dc-rabbitmq:
        condition: service_healthy
      dc-db-migrate:
        condition: service_completed_successfully
