include:
  - multicast/proxy/docker-compose.yaml
  - cache/docker-compose.yaml

services:
  dc-ranges-rabbitmq:
    container_name: dc-ranges-rabbitmq
    hostname: ranges-rabbitmq
    image: rabbitmq:management
    networks:
      - displaycontroller
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 3
