services:
  dc-images:
    container_name: dc-images
    hostname: images
    networks:
      - displaycontroller      
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./files:/app/files"
    depends_on:
      dc-db-migrate:
        condition: service_completed_successfully