services:
  dc-images:
    container_name: dc-images
    image: ghcr.io/svenfinn/dc-images
    hostname: images
    networks:
      - displaycontroller
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        - logger=../../logger
    volumes:
      - "./files:/app/files"
    depends_on:
      dc-db-migrate:
        condition: service_completed_successfully
