services:
  dc-evaluations:
    hostname: evaluations
    container_name: dc-evaluations
    networks:
      - displaycontroller
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      dc-db-migrate:
        condition: service_completed_successfully
