services:
  dc-evaluations:
    hostname: evaluations
    container_name: dc-evaluations
    networks:
      - displaycontroller
    build: 
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        - local-db=../../database/local
    depends_on:
      dc-db-migrate:
        condition: service_completed_successfully
      dc-check-server:
        condition: service_started
