services:
  dc-screens-man:
    container_name: dc-screens-man
    image: ghcr.io/svenfinn/dc-screens-man
    hostname: screens-manager
    networks:
      - displaycontroller
    build:
      context: .
      dockerfile: ./Dockerfile
      additional_contexts:
        - local-db=../../database/local
        - images=../images
        - evaluations=../evaluations
        - ranges=../../ranges/types
        - logger=../../logger
      args:
        - SELF_DB_URL=${SELF_DB_URL}

    depends_on:
      dc-db-migrate:
        condition: service_completed_successfully
      dc-rabbitmq:
        condition: service_healthy
