services:
  dc-ranges-multicast-proxy:
    container_name: dc-ranges-multicast-proxy
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      dc-db-migrate:
        condition: service_completed_successfully
      dc-rabbitmq:
        condition: service_healthy
