services:
  dc-ranges-multicast-proxy:
    container_name: dc-ranges-multicast-proxy
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MULTICAST_MSG_MIN_LENGTH=${MULTICAST_MSG_MIN_LENGTH}
    depends_on:
      dc-db-migrate:
        condition: service_completed_successfully
      dc-rabbitmq:
        condition: service_healthy
