services:
  dc-reverse-proxy:
    image: ghcr.io/svenfinn/dc-reverse-proxy:${APP_VERSION}
    container_name: dc-reverse-proxy
    hostname: reverse_proxy
    restart: on-failure
    build: .
    ports:
      - "${APP_PORT}:80"
    networks:
      - displaycontroller
