services:
  dc-sync-time:
    container_name: dc-sync-time
    image: ghcr.io/svenfinn/dc-sync-time
    hostname: sync-time
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        - local-db=../database/local
        - smdb-db=../database/smdb
        - logger=../logger
      args:
        - SELF_DB_URL=${SELF_DB_URL}
        - MEYTON_DB_PASS=${MEYTON_DB_PASS}
        - MEYTON_DB_USER=${MEYTON_DB_USER}
    networks:
      - displaycontroller
    depends_on:
      - dc-check-server
    cap_add:
      - SYS_TIME
