services:
  dc-ranges-merger:
    container_name: dc-ranges-merger
    hostname: ranges
    image: ghcr.io/svenfinn/dc-ranges-merger:${APP_VERSION}
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SELF_DB_HOST=${SELF_DB_HOST}
        - SELF_DB_USER=${SELF_DB_USER}
        - SELF_DB_PASS=${SELF_DB_PASS}
        - SELF_DB_NAME=${SELF_DB_NAME}
        - CACHE_REFRESH_INTERVAL=${CACHE_REFRESH_INTERVAL}
      additional_contexts:
        - local-db=../../database/local
        - range-types=../types
        - range-ttl=../ttl
        - logger=../../logger
    networks:
      - displaycontroller
    depends_on:
      dc-rabbitmq:
        condition: service_healthy
      dc-db-migrate:
        condition: service_completed_successfully
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
