services:
  dc-server-state:
    container_name: dc-server-state
    hostname: server-state
    image: ghcr.io/svenfinn/dc-server-state:${APP_VERSION}
    restart: on-failure
    networks:
      - displaycontroller
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        - local-db=../../lib/database/local
        - smdb=../../lib/database/smdb
        - screen-types=../../screens/types
        - logger=../../lib/logger
        - endpoints=../../lib/endpoints
        - server-state-contract=../contract
      args:
        - MIN_SM_VERSION=${MIN_SM_VERSION}
        - MAX_SM_VERSION=${MAX_SM_VERSION}
        - SM_SSH_USER=${SM_SSH_USER}
        - SM_SSH_PASS=${SM_SSH_PASS}
        - SM_DB_USER=${SM_DB_USER}
        - SM_DB_PASS=${SM_DB_PASS}
        - SELF_DB_HOST=${SELF_DB_HOST}
        - SELF_DB_USER=${SELF_DB_USER}
        - SELF_DB_PASS=${SELF_DB_PASS}
        - SELF_DB_NAME=${SELF_DB_NAME}
    depends_on:
      dc-database:
        condition: service_healthy
      dc-db-migrate:
        condition: service_completed_successfully
      dc-rabbitmq:
        condition: service_healthy
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
